services:
  mobile_arm_hardware:
    build:
      context: ./
      dockerfile: docker/hardware/Dockerfile
    image: mobile_arm_hardware
    user: ros
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
      - ROS_DISCOVERY_SERVER
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./fastdds.xml:/fastdds.xml
    command: ros2 launch mobile_arm_bringup hardware.launch.py