version: '3'
services:
  mobile_arm_moveit:
    image: delicjusz/pioneer_3dx_with_manipulator:lab1.5
    user: ros
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
      - DISPLAY
    volumes:
      - ./fastdds.xml:/etc/ros/fastdds.xml
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true 
    tty: true
    command: ros2 launch mobile_arm_moveit moveit_blank.launch.py use_sim:=False