version: '3'
services:
  mobile_arm_hardware:
    build:
      context: ./
      dockerfile: docker/hardware/Dockerfile
    image: mobile_arm_hardware
    user: ros
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - ROS_DOMAIN_ID
    volumes:
      - ./cyclonedds_ariadna.xml:/cyclonedds.xml
      - ./src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/dri:/dev/dri
    stdin_open: true 
    tty: true
    command: ros2 launch mobile_arm_bringup hardware.launch.py
  mobile_arm_moveit:
    build:
      context: ./
      dockerfile: docker/hardware/Dockerfile
    image: mobile_arm_hardware
    user: ros
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - ROS_DOMAIN_ID
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
      - ./src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true 
    tty: true
    command: ros2 launch mobile_arm_moveit moveit_blank.launch.py