services:
  mobile_arm_hardware:
    image: delicjusz/pioneer_3dx_with_manipulator:lab1.5
    user: ros
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./fastdds.xml:/fastdds.xml
    command: ros2 launch mobile_arm_bringup hardware.launch.py
  mobile_arm_moveit:
    image: delicjusz/pioneer_3dx_with_manipulator:lab1.5
    user: ros
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /tmp/.X11-unix:/tmp/.X11-unix
    volumes:
      - ./fastdds.xml:/fastdds.xml
      - /dev/dri:/dev/dri
    command: ros2 launch mobile_arm_moveit moveit_blank.launch.py