services:
  mobile_arm_hardware:
    image: delicjusz/pioneer_3dx_with_manipulator:lab1.5
    user: ros
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
      - ROS_DISCOVERY_SERVER
    volumes:
      - ./fastdds.xml:/etc/ros/fastdds.xml
    stdin_open: true 
    tty: true