<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:include filename="$(find mobile_arm_description)/description/inertia_tensors.xacro"/>
  <xacro:include filename="chassis.xacro"/>
  <xacro:include filename="wheel.xacro"/>
  <xacro:include filename="battery_block.xacro"/>
  <xacro:include filename="swivel.xacro"/>
  <xacro:include filename="sonar.xacro"/>
  <xacro:property name="wheel_radius" value="0.097" />
  
  <!-- name="body" parent="base_link" --> 
  <xacro:macro name="vehicle_body" params="name parent"> 
        
    <!-- base_link -->
    <link name="${parent}"/>
    
    <!-- Chassis -->
    <xacro:pioneer_chassis name="${name}" parent="${parent}" xyz="0 0 0.068" rpy="0 0 0"/>
    
    <!-- Front Sonar -->
    <xacro:pioneer_sonar name="sonar" parent="${name}" xyz="0.109 0 0.15" rpy="0 0 0"/>      
    
    <!-- Akku0 -->
    <xacro:pioneer_battery_block name="battery0" parent="${name}" x="-0.14" y="0.00"  z="${0.13-0.068}" mass="25.5" />  
    
    <!-- Wheels -->
    <!-- <xacro:property name="contact_data">
        <mu1 value="0.7"/>
        <mu2 value="0.7"/>
        <minDepth value="0.002"/>
        <kp value="1000000.0"/>
        <kd value="10.0"/>
    </xacro:property>  -->

    <!-- Swivels -->
    <xacro:pioneer_swivel  name="swivel"    parent="${parent}"  xyz="-0.185 0    0.0555" rpy="0 0 0"/>              

    <!-- Wheels -->
    <xacro:pioneer_wheel name="right" parent="${parent}"  xyz=" 0    -0.16 ${wheel_radius - 0.005}" rpy="0 0 0" radius="${wheel_radius}"/>
    <xacro:pioneer_wheel name="left"  parent="${parent}"  xyz=" 0     0.16 ${wheel_radius - 0.005}" rpy="0 0 0" radius="${wheel_radius}"/>
    
  </xacro:macro>
</robot>
